// <auto-generated />
using System;
using Dharma.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dharma.Migrations
{
    [DbContext(typeof(DharmaDbContext))]
    partial class DharmaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Arcadia.Models.Usuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("telefono")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsuariosDharma", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Jose Miguel",
                            direccion = "C/ La Braille 16",
                            password = "josemi89",
                            telefono = 636041446
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Bartolo",
                            direccion = "C/ La Lazarillo 29",
                            password = "bartolo78",
                            telefono = 987986797
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
